# Site settings
title: Sam and Cora Wedding - Save the date
email: sam.younger@gmail.com
description: >
  This is a website for Sam and Cora's wedding 2018 save the date invitations
baseurl: ""
url: "http://save-the-date.samandcora.com"
github_username:  samyounger

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock
