# Site settings
title: Sam and Cora Wedding
email: sam.younger@gmail.com
description: >
  This is a website for Sam and Cora's wedding 2018
baseurl: ""
url: "http://samandcora.com"
github_username:  samyounger

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock
